# frontend: static webpage
<VirtualHost *:80>
    ServerName 192.168.164.129
    DocumentRoot /var/www/frontend

    <Directory /var/www/frontend>
        AllowOverride All
        Require all granted
        # allow Vite router work 
        FallbackResource /index.html
    </Directory>
</VirtualHost>

# backend：reverse proxy to Node.js
<VirtualHost *:3000>
    ServerName your-domain-or-IP

    ProxyPreserveHost On
    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/
</VirtualHost>